### PR TITLE
Added some nice, ambient music

### PR DESCRIPTION
**Pull request by draseil**
I hope you like it :3

### CODE REVIEW

**Comment by kirbyUK** [comment]
Is it good to have all the music controls in main? I think a seperate 'music.h' and 'music.c' would probably be better. ~~Also, does SDL support mp3? I know SFML doesn't.~~ EDIT: Looks like it does.

**Comment by draseil** [comment]
SFML does support mp3 (if I remember correctly) but CSFML has ridiculously long function names and I didn't manage to link it properly.
I'll organise it a bit; I just /really/ wanted to have the music there :P

**Comment by kirbyUK** [comment]
[Pretty sure it doesn't](http://www.sfml-dev.org/documentation/2.2/classsf_1_1SoundBuffer.php#a2be6a8025c97eb622a7dff6cf2594394). Doesn't really matter though, we're not using SFML :stuck_out_tongue: 

The other issue is distribution rights I guess, we can't just go sticking up anyone's music for free download. Where did you get it?

**Comment by draseil** [comment]
True, yeah hahahaha

I just used youtube-dl and then ffmpeg
Not the smartest choice, but it's not like we're really making a profit off this or anything

**Comment by draseil** [comment]
Ok, I'm going to merge this

**Pull request merged**
