### PR TITLE
Let's ~~DANCE~~!

### PR DESCRIPTION
**Pull request by wbrbr**

### CODE REVIEW

**Comment by vhakulinen** [comment]
Move the audio init/cleanup to the `main.c` like other components and use `fprintf(stderr, "msg %s", "err")` for error messages.

**Comment by kirbyUK** [comment]
You forgot to add instructions on how to build 'music.o' in the Makefile, so this will not compile. It's quite simple, just add the following to (above clean if you could please):

``` Makefile
music.o: $(SRC)/music.h $(SRC)/music.c
    $(CC) $(FLAGS) $(SRC)/music.c
```

Which reminds me the rest of them need `$(SRC)/` prepended to them as well in the rule.

**Comment by wbrbr** [comment]
I just made a new Makefile which automatically lists and compile the source files (https://gist.github.com/nounoursheureux/a5788407c55ac6a79861) . Do you want me to add it to this PR or do you think it would be better to wait ?

**Comment by kirbyUK** [comment]
If you want to be all proper about it then this should probably go in a separate PR, but I don't really mind so if it works go for it.

**Comment by wbrbr** [comment]
Ok, I added it :+1:

**Pull request merged**
