### PR TITLE
Added assets directory, updated Makefile

### PR DESCRIPTION
**Pull request by kirbyUK**
Not too sure about the Makefile but I've done similar for all my [other projects](https://github.com/kirbyUK/platformer), so I think it's fine?

### CODE REVIEW

**Comment by wbrbr** [comment]
With your Makefile `make` won't recompile everything when a single file is modified so for me this is better :+1:

**Comment by kirbyUK** [comment]
That was part of the intention, yes. It does mean you have to update it every time you add a new file though, but I don't think that's too hard to manage.

**Comment by wbrbr** [comment]
We could also make a src/ directory and the Makefile would list all the files in this directory and compile them automatically.

**Comment by kirbyUK** [comment]
You could certainly do this. I'm busy at the moment so if someone else wants to merge and implement this go ahead, otherwise I'll have a look later tonight.

**Comment by vhakulinen** [comment]
:+1:

**Comment by vhakulinen** [comment]
> We could also make a src/ directory and the Makefile would list all the files in this directory and compile them automatically.

Open new PR for this is someone decides to do it.

**Pull request merged**
